from GridCell import GridCell
def grid():
    grid1 = [
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("player", "red", None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("player", "blue", None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("target", "yellow", None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("player", "green", None), GridCell("empty", None, None),
         GridCell("target", "green", None), GridCell("wall", None, None), GridCell("target", "red", None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("player", "yellow", None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("target", "blue", None), GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None)],
    ]

    grid2 = [
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("player", "yellow", None), GridCell("player", "red", None),
         GridCell("player", "blue", None), GridCell("player", "green", None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("target", "yellow", None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("target", "green", None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("wall", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("target", "blue", None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("wall", None, None), GridCell("empty", None, None),
         GridCell("target", "red", None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("empty", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None)],
    ]
    grid3 = [
        [GridCell("empty", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("target", "yellow", None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("player", "blue", None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("player", "yellow", None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("player", "red", None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("target", "red", None), GridCell("empty", None, None), GridCell("player", "green", None),
         GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("target", "blue", None), GridCell("empty", None, None),
         GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("target", "green", None), GridCell("wall", None, None),
         GridCell("wall", None, None)],
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("empty", None, None)],
    ]
    grid4 = [
        [GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None)],

        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("player", "red", None), GridCell("target", "yellow", None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None)],

        [GridCell("wall", None, None), GridCell("target", "blue", None), GridCell("player", "pink", None),
         GridCell("player", "blue", None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None)],

        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("fake_target", "green", "pink"),
         GridCell("wall", None, None),
         GridCell("target", "red", None), GridCell("empty", None, None), GridCell("wall", None, None),
         GridCell("fake_target", "yellow", "green"), GridCell("wall", None, None)],

        [GridCell("wall", None, None),GridCell("wall", None, None),GridCell("wall", None, None),GridCell("wall", None, None)
            ,GridCell("wall", None, None),GridCell("wall", None, None),GridCell("wall", None, None)
            ,GridCell("wall", None, None),GridCell("wall", None, None)]
    ]
    grid5 = [
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("target", "red", None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("target", "green", None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None)],
        [GridCell("wall", None, None), GridCell("target", "yellow", None), GridCell("wall", None, None),
         GridCell("empty", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("empty", None, None),
         GridCell("empty", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("player", "blue", None),
         GridCell("player", "yellow", None), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("empty", None, None), GridCell("empty", None, None),
         GridCell("wall", None, None),
         GridCell("empty", None, None), GridCell("empty", None, None), GridCell("wall", None, None),
         GridCell("player", "red", None),
         GridCell("fake_target", "green","blue"), GridCell("wall", None, None)],
        [GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None), GridCell("wall", None, None),
         GridCell("wall", None, None),
         GridCell("wall", None, None), GridCell("wall", None, None)],
    ]

    return [grid1, grid2, grid3, grid4,grid5]
